### ISSUE TITLE
[Bug]: Cannot read properties of null (reading 'setupContext')

### ISSUE THREAD

**Issue by alexeyPalshin** [webdevnerdstuff/vuetify-inline-fields#25] opened 2023-08-01 18:36 UTC
### Bug description

an Uncaught  TypeError is thrown: Cannot read properties of null (reading 'setupContext')
   "vuetify": "3.2.5",
   "vue": "3.2.31",
typescript, composition API

### Steps to reproduce

1. Install using npm package manager
2. Load all components into App
3. Use VInlineTextField in the server data table item slot

### Relevant log output

```shell
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'setupContext')
    at getContext (runtime-core.esm-bundler.js:3200:12)
    at useAttrs (runtime-core.esm-bundler.js:3159:10)
    at setup (vuetify-inline-fields.es.js:3114:45)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7056:29)
    at setupComponent (runtime-core.esm-bundler.js:7012:11)
    at mountComponent (runtime-core.esm-bundler.js:4922:13)
    at processComponent (runtime-core.esm-bundler.js:4897:17)
    at patch (runtime-core.esm-bundler.js:4489:21)
    at mountChildren (runtime-core.esm-bundler.js:4685:13)
getContext @ runtime-core.esm-bundler.js:3200
useAttrs @ runtime-core.esm-bundler.js:3159
setup @ vuetify-inline-fields.es.js:3114
callWithErrorHandling @ runtime-core.esm-bundler.js:155
setupStatefulComponent @ runtime-core.esm-bundler.js:7056
setupComponent @ runtime-core.esm-bundler.js:7012
mountComponent @ runtime-core.esm-bundler.js:4922
processComponent @ runtime-core.esm-bundler.js:4897
patch @ runtime-core.esm-bundler.js:4489
mountChildren @ runtime-core.esm-bundler.js:4685
processFragment @ runtime-core.esm-bundler.js:4856
patch @ runtime-core.esm-bundler.js:4482
mountChildren @ runtime-core.esm-bundler.js:4685
mountElement @ runtime-core.esm-bundler.js:4594
processElement @ runtime-core.esm-bundler.js:4566
patch @ runtime-core.esm-bundler.js:4486
componentUpdateFn @ runtime-core.esm-bundler.js:5037
run @ reactivity.esm-bundler.js:167
setupRenderEffect @ runtime-core.esm-bundler.js:5156
mountComponent @ runtime-core.esm-bundler.js:4939
processComponent @ runtime-core.esm-bundler.js:4897
patch @ runtime-core.esm-bundler.js:4489
mountChildren @ runtime-core.esm-bundler.js:4685
processFragment @ runtime-core.esm-bundler.js:4856
patch @ runtime-core.esm-bundler.js:4482
mountChildren @ runtime-core.esm-bundler.js:4685
mountElement @ runtime-core.esm-bundler.js:4594
processElement @ runtime-core.esm-bundler.js:4566
patch @ runtime-core.esm-bundler.js:4486
componentUpdateFn @ runtime-core.esm-bundler.js:5037
run @ reactivity.esm-bundler.js:167
setupRenderEffect @ runtime-core.esm-bundler.js:5156
mountComponent @ runtime-core.esm-bundler.js:4939
processComponent @ runtime-core.esm-bundler.js:4897
patch @ runtime-core.esm-bundler.js:4489
mountChildren @ runtime-core.esm-bundler.js:4685
processFragment @ runtime-core.esm-bundler.js:4856
patch @ runtime-core.esm-bundler.js:4482
patchKeyedChildren @ runtime-core.esm-bundler.js:5298
patchChildren @ runtime-core.esm-bundler.js:5205
processFragment @ runtime-core.esm-bundler.js:4886
patch @ runtime-core.esm-bundler.js:4482
patchKeyedChildren @ runtime-core.esm-bundler.js:5262
patchChildren @ runtime-core.esm-bundler.js:5205
processFragment @ runtime-core.esm-bundler.js:4886
patch @ runtime-core.esm-bundler.js:4482
componentUpdateFn @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:167
updateComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4901
patch @ runtime-core.esm-bundler.js:4489
patchKeyedChildren @ runtime-core.esm-bundler.js:5262
patchChildren @ runtime-core.esm-bundler.js:5205
patchElement @ runtime-core.esm-bundler.js:4721
processElement @ runtime-core.esm-bundler.js:4569
patch @ runtime-core.esm-bundler.js:4486
patchKeyedChildren @ runtime-core.esm-bundler.js:5262
patchChildren @ runtime-core.esm-bundler.js:5205
processFragment @ runtime-core.esm-bundler.js:4886
patch @ runtime-core.esm-bundler.js:4482
patchKeyedChildren @ runtime-core.esm-bundler.js:5262
patchChildren @ runtime-core.esm-bundler.js:5205
processFragment @ runtime-core.esm-bundler.js:4886
patch @ runtime-core.esm-bundler.js:4482
patchKeyedChildren @ runtime-core.esm-bundler.js:5262
patchChildren @ runtime-core.esm-bundler.js:5205
patchElement @ runtime-core.esm-bundler.js:4721
processElement @ runtime-core.esm-bundler.js:4569
patch @ runtime-core.esm-bundler.js:4486
patchKeyedChildren @ runtime-core.esm-bundler.js:5262
patchChildren @ runtime-core.esm-bundler.js:5205
patchElement @ runtime-core.esm-bundler.js:4721
processElement @ runtime-core.esm-bundler.js:4569
patch @ runtime-core.esm-bundler.js:4486
patchKeyedChildren @ runtime-core.esm-bundler.js:5262
patchChildren @ runtime-core.esm-bundler.js:5205
patchElement @ runtime-core.esm-bundler.js:4721
processElement @ runtime-core.esm-bundler.js:4569
patch @ runtime-core.esm-bundler.js:4486
componentUpdateFn @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:167
updateComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4901
patch @ runtime-core.esm-bundler.js:4489
componentUpdateFn @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:167
updateComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4901
patch @ runtime-core.esm-bundler.js:4489
patchKeyedChildren @ runtime-core.esm-bundler.js:5262
patchChildren @ runtime-core.esm-bundler.js:5205
patchElement @ runtime-core.esm-bundler.js:4721
processElement @ runtime-core.esm-bundler.js:4569
patch @ runtime-core.esm-bundler.js:4486
componentUpdateFn @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:167
callWithErrorHandling @ runtime-core.esm-bundler.js:155
flushJobs @ runtime-core.esm-bundler.js:394
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:285
queueJob @ runtime-core.esm-bundler.js:279
(anonymous) @ runtime-core.esm-bundler.js:5139
triggerEffects @ reactivity.esm-bundler.js:359
triggerRefValue @ reactivity.esm-bundler.js:957
set value @ reactivity.esm-bundler.js:1001
SET_EMPLOYER_GROUPS @ employerGroups.ts:55
fetchEmployerGroups @ employerGroups.ts:24
await in fetchEmployerGroups (async)
(anonymous) @ pinia.esm-browser.js:1277
employerGroupsRequest @ ClientEmployerGroups.vue:32
paramsUpdatedHandler @ ClientEmployerGroups.vue:37
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
emit$1 @ runtime-core.esm-bundler.js:718
(anonymous) @ runtime-core.esm-bundler.js:7232
_createVNode.onUpdate:options._cache.<computed>._cache.<computed> @ EmployerGroupList.vue:31
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
emit$1 @ runtime-core.esm-bundler.js:718
watch.deep @ options.ts:40
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
job @ runtime-core.esm-bundler.js:1779
doWatch @ runtime-core.esm-bundler.js:1824
watch @ runtime-core.esm-bundler.js:1665
useOptions @ options.ts:38
setup @ VDataTableServer.tsx:80
setup @ defineComponent.tsx:116
callWithErrorHandling @ runtime-core.esm-bundler.js:155
setupStatefulComponent @ runtime-core.esm-bundler.js:7056
setupComponent @ runtime-core.esm-bundler.js:7012
mountComponent @ runtime-core.esm-bundler.js:4922
processComponent @ runtime-core.esm-bundler.js:4897
patch @ runtime-core.esm-bundler.js:4489
mountChildren @ runtime-core.esm-bundler.js:4685
mountElement @ runtime-core.esm-bundler.js:4594
processElement @ runtime-core.esm-bundler.js:4566
patch @ runtime-core.esm-bundler.js:4486
componentUpdateFn @ runtime-core.esm-bundler.js:5037
run @ reactivity.esm-bundler.js:167
setupRenderEffect @ runtime-core.esm-bundler.js:5156
mountComponent @ runtime-core.esm-bundler.js:4939
processComponent @ runtime-core.esm-bundler.js:4897
patch @ runtime-core.esm-bundler.js:4489
mountChildren @ runtime-core.esm-bundler.js:4685
processFragment @ runtime-core.esm-bundler.js:4856
patch @ runtime-core.esm-bundler.js:4482
mountChildren @ runtime-core.esm-bundler.js:4685
mountElement @ runtime-core.esm-bundler.js:4594
processElement @ runtime-core.esm-bundler.js:4566
patch @ runtime-core.esm-bundler.js:4486
componentUpdateFn @ runtime-core.esm-bundler.js:5037
run @ reactivity.esm-bundler.js:167
setupRenderEffect @ runtime-core.esm-bundler.js:5156
mountComponent @ runtime-core.esm-bundler.js:4939
processComponent @ runtime-core.esm-bundler.js:4897
patch @ runtime-core.esm-bundler.js:4489
componentUpdateFn @ runtime-core.esm-bundler.js:5037
run @ reactivity.esm-bundler.js:167
setupRenderEffect @ runtime-core.esm-bundler.js:5156
mountComponent @ runtime-core.esm-bundler.js:4939
processComponent @ runtime-core.esm-bundler.js:4897
patch @ runtime-core.esm-bundler.js:4489
componentUpdateFn @ runtime-core.esm-bundler.js:5037
run @ reactivity.esm-bundler.js:167
setupRenderEffect @ runtime-core.esm-bundler.js:5156
mountComponent @ runtime-core.esm-bundler.js:4939
processComponent @ runtime-core.esm-bundler.js:4897
patch @ runtime-core.esm-bundler.js:4489
mountChildren @ runtime-core.esm-bundler.js:4685
processFragment @ runtime-core.esm-bundler.js:4856
patch @ runtime-core.esm-bundler.js:4482
patchKeyedChildren @ runtime-core.esm-bundler.js:5403
patchChildren @ runtime-core.esm-bundler.js:5205
patchElement @ runtime-core.esm-bundler.js:4721
processElement @ runtime-core.esm-bundler.js:4569
patch @ runtime-core.esm-bundler.js:4486
componentUpdateFn @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:167
updateComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4901
patch @ runtime-core.esm-bundler.js:4489
componentUpdateFn @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:167
updateComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4901
patch @ runtime-core.esm-bundler.js:4489
componentUpdateFn @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:167
updateComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4901
patch @ runtime-core.esm-bundler.js:4489
componentUpdateFn @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:167
updateComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4901
patch @ runtime-core.esm-bundler.js:4489
patchKeyedChildren @ runtime-core.esm-bundler.js:5262
patchChildren @ runtime-core.esm-bundler.js:5205
processFragment @ runtime-core.esm-bundler.js:4886
patch @ runtime-core.esm-bundler.js:4482
patchKeyedChildren @ runtime-core.esm-bundler.js:5262
patchChildren @ runtime-core.esm-bundler.js:5205
patchElement @ runtime-core.esm-bundler.js:4721
processElement @ runtime-core.esm-bundler.js:4569
patch @ runtime-core.esm-bundler.js:4486
patchKeyedChildren @ runtime-core.esm-bundler.js:5262
patchChildren @ runtime-core.esm-bundler.js:5205
patchElement @ runtime-core.esm-bundler.js:4721
processElement @ runtime-core.esm-bundler.js:4569
patch @ runtime-core.esm-bundler.js:4486
componentUpdateFn @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:167
updateComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4901
patch @ runtime-core.esm-bundler.js:4489
patchBlockChildren @ runtime-core.esm-bundler.js:4806
processFragment @ runtime-core.esm-bundler.js:4867
patch @ runtime-core.esm-bundler.js:4482
componentUpdateFn @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:167
callWithErrorHandling @ runtime-core.esm-bundler.js:155
flushJobs @ runtime-core.esm-bundler.js:394
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:285
queueJob @ runtime-core.esm-bundler.js:279
(anonymous) @ runtime-core.esm-bundler.js:5139
triggerEffects @ reactivity.esm-bundler.js:359
triggerRefValue @ reactivity.esm-bundler.js:957
set value @ reactivity.esm-bundler.js:1001
set @ reactivity.esm-bundler.js:1016
_createVNode.onUpdate:modelValue._cache.<computed>._cache.<computed> @ Client.vue:141
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
emit$1 @ runtime-core.esm-bundler.js:718
set @ proxiedModel.ts:59
set value @ reactivity.esm-bundler.js:1106
onUpdate:modelValue @ VTabs.tsx:93
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
emit$1 @ runtime-core.esm-bundler.js:718
set @ proxiedModel.ts:59
set value @ reactivity.esm-bundler.js:1106
select @ group.ts:252
toggle @ group.ts:140
onClick @ VBtn.tsx:139
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:366
```

### Reproduction link

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by webdevnerdstuff** [comment] 2023-08-03 18:01
@alexeyPalshin Did you provide a reproduction link? Just want to check in case it's my bug template form that messed up.

**Comment by alexeyPalshin** [comment] 2023-08-04 08:12
Hello, your bug template is working. I deliberately sent an invalid value to the reproduction link field. since I could not find your library in the dependencies on any of the platforms (JSFiddle, CodeSandbox etc.). Today I wanted to send you a link to the github repository , but when I created an empty project, I could not reproduce the problem) it only reproduces on my working project.

**Comment by webdevnerdstuff** [comment] 2023-08-04 19:46
It believe it won't be in any online cdn's yet since it's still in beta and only has pre-releases.

Since it happens in your project, are you able to share or show that project, perhaps I can see if something is off?

**Comment by alexeyPalshin** [comment] 2023-08-07 06:01
No, sorry.  I won't show the project itself - it's a client project and I don't think it's worth showing it. I will try somehow to reproduce on an empty project and then we'll seeю.

**Comment by webdevnerdstuff** [comment] 2023-10-21 01:54
Closing the issue since there hasn't been updates.

**Closed** 2023-10-21 01:53 UTC
Labels: bug
